#!/bin/bash

# Exemplo de curl para criar contrato de aluguel com fiador
curl -X POST http://localhost:3333/contrato-aluguel-fiador \
  -H "Content-Type: application/json" \
  -d '{
    "nomeLocador": "João Silva Santos",
    "nomeLocatario": "Maria Oliveira Costa",
    "fiador": "Luiz Henrique Souza",
    "descricaoImovel": "Apartamento 70m2",
    "valorAluguel": "R$ 2.000,00",
    "prazoLocacao": "12 meses",
    "dataInicio": "01/01/2024",
    "dataFim": "31/12/2024",
    "logradouroImovel": "Rua das Flores",
    "numeroImovel": "123",
    "complementoImovel": "Apto 101",
    "cepImovel": "01234-567",
    "bairroImovel": "Centro",
    "cidadeImovel": "São Paulo",
    "ufImovel": "SP",
    "nacionalidadeLocador": "Brasileira",
    "estadoCivilLocador": "Solteiro",
    "ocupacaoLocador": "Empresário",
    "rgLocador": "12.345.678-9",
    "orgaoExpedidorLocador": "SSP",
    "ufExpedidorLocador": "SP",
    "cpfLocador": "123.456.789-10",
    "logradouroLocador": "Rua dos Comerciantes",
    "numeroLocador": "456",
    "complementoLocador": "Apto 101",
    "bairroLocador": "Vila Madalena",
    "ufLocador": "SP",
    "cidadeLocador": "São Paulo",
    "cepLocador": "05434-123",
    "nacionalidadeLocatario": "Brasileira",
    "estadoCivilLocatario": "Casada",
    "ocupacaoLocatario": "Advogada",
    "rgLocatario": "98.765.432-1",
    "orgaoExpedidorLocatario": "SSP",
    "ufExpedidorLocatario": "SP",
    "cpfLocatario": "987.654.321-10",
    "logradouroLocatario": "Rua dos Advogados",
    "numeroLocatario": "789",
    "complementoLocatario": "Casa",
    "bairroLocatario": "Jardins",
    "cidadeLocatario": "São Paulo",
    "cepLocatario": "01234-789",
    "finalidadeLocacao": "Residencial",
    "valorAluguelEscrito": "dois mil reais",
    "bancoLocador": "Itaú",
    "agenciaLocador": "0123",
    "contaLocador": "12345-6",
    "chavePixLocador": "joao@empresa.com",
    "emailLocador": "joao@empresa.com",
    "nomeCorretor": "Carlos Imobiliária",
    "nacionalidadeCorretor": "Brasileira",
    "estadoCivilCorretor": "Casado",
    "cpfCorretor": "555.666.777-88",
    "rgCorretor": "55.666.777-8",
    "orgaoExpedidorCorretor": "SSP",
    "ufExpedidorCorretor": "SP",
    "creciCorretor": "12345-F",
    "logradouroCorretor": "Rua dos Corretores",
    "numeroCorretor": "321",
    "cidadeCorretor": "São Paulo",
    "bairroCorretor": "Centro",
    "ufCorretor": "SP",
    "cepCorretor": "01234-000",
    "honorariosCorretor": "R$ 200,00",
    "bancoCorretor": "Banco do Brasil",
    "agenciaCorretor": "1234",
    "contaCorretor": "56789-0",
    "chavePixCorretor": "carlos@corretor.com",
    "contaContrato": 1,
    "nacionalidadeFiador": "Brasileira",
    "ocupacaoFiador": "Engenheiro",
    "estadoCivilFiador": "Solteiro",
    "rgFiador": "21.547.963-7",
    "orgaoExpedidorFiador": "SSP",
    "ufExpedidorFiador": "SP",
    "cpfFiador": "456.123.789-00",
    "logradouroFiador": "Rua dos Engenheiros",
    "numeroFiador": "654",
    "complementoFiador": "Casa",
    "cepFiador": "01234-321",
    "bairroFiador": "Zona Leste",
    "cidadeFiador": "São Paulo",
    "ufFiador": "SP",
    "foroContrato": "São Paulo"
  }'
