#!/bin/bash

# Exemplo de curl para criar contrato de aluguel com caução
curl -X POST http://localhost:3333/contrato-aluguel-caucao \
  -H "Content-Type: application/json" \
  -d '{
    "valorMensalAluguelEscrito": "dois mil reais",
    "locador": "João Silva Santos",
    "cpfLocador": "123.456.789-10",
    "estadoCivilLocador": "Solteiro",
    "profissaoLocador": "Empresário",
    "rgLocador": "12.345.678-9",
    "locatario": "Maria Oliveira Costa",
    "cpfLocatario": "987.654.321-10",
    "estadoCivilLocatario": "Casada",
    "profissaoLocatario": "Advogada",
    "rgLocatario": "98.765.432-1",
    "nomeConjuge": "Pedro Costa",
    "cpfConjuge": "111.222.333-44",
    "finalidade": "Residencial",
    "objContrato": "Apartamento",
    "endObjeto": "Rua das Flores",
    "numObjeto": "123",
    "bairroObjeto": "Centro",
    "cidadeObjeto": "São Paulo",
    "ufObjeto": "SP",
    "cepObjeto": "01234-567",
    "nacionalidadeLocador": "Brasileira",
    "orgaoExpedidor": "SSP",
    "ufExpedicao": "SP",
    "ruaLocador": "Rua dos Comerciantes",
    "numLocador": "456",
    "compLocador": "Apto 101",
    "bairroLocador": "Vila Madalena",
    "cepLocador": "05434-123",
    "nacionalidadeLocatario": "Brasileira",
    "orgaoExpedidorLocatario": "SSP",
    "ufExpedicaoLocatario": "SP",
    "ruaLocatario": "Rua dos Advogados",
    "numLocatario": "789",
    "compLocatario": "Casa",
    "bairroLocatario": "Jardins",
    "ufLocatario": "SP",
    "cepLocatario": "01234-789",
    "cidadeLocatario": "São Paulo",
    "ufLocador": "SP",
    "cidadeLocador": "São Paulo",
    "nomeCorretor": "Carlos Imobiliária",
    "nacionalidadeCorretor": "Brasileira",
    "estadoCivilCorretor": "Casado",
    "profissaoCorretor": "Corretor",
    "cpfCorretor": "555.666.777-88",
    "rgCorretor": "55.666.777-8",
    "orgaoExpedidorCorretor": "SSP",
    "ufExpedicaoCorretor": "SP",
    "numCreci": "12345-F",
    "ruaCorretor": "Rua dos Corretores",
    "numCorretor": "321",
    "cepCorretor": "01234-000",
    "bairroCorretor": "Centro",
    "cidadeCorretor": "São Paulo",
    "ufCorretor": "SP",
    "valorServicoCorretor": "R$ 200,00",
    "valorServicoEscrito": "duzentos reais",
    "bancoCorretor": "Banco do Brasil",
    "agCorretor": "1234",
    "contaCorretor": "56789-0",
    "pixCorretor": "carlos@corretor.com",
    "prazoVigencia": "12 meses",
    "inicio": "01/01/2024",
    "termino": "31/12/2024",
    "valorMensal": "R$ 2.000,00",
    "vencimento": "todo dia 10",
    "finalidadeLocacao": "Residencial",
    "valorGarantiaCaucao": "R$ 6.000,00",
    "diaVencimento": "10",
    "ciaEletrica": "CPFL",
    "bancoLocador": "Itaú",
    "agLocador": "0123",
    "contaLocador": "12345-6",
    "titularConta": "João Silva Santos"
  }'
