import { ContractDataDTO } from "../../domain/pdf/dtos/ContractDataDTO";
import { dateProvider } from "../dateProvider/dateProvider";
import { v4 as uuidV4 } from "uuid"
import fs from "fs"
import { S3 } from "aws-sdk";
import { uploadProvider } from "../uploadProvider/uploadProvider";
 
const pdfMaker = require("pdf-maker");

export class PdfProvider {
    async generate({
            valorMensalAluguelEscrito,
            finalidade,
            locador,
            cpfLocador,
            estadoCivilLocador,
            profissaoLocador,
            rgLocador,
            locatario,
            cpfLocatario,
            estadoCivilLocatario,
            profissaoLocatario,
            rgLocatario,
            nomeConjuge,
            cpfConjuge,
            objContrato,
            endObjeto,
            numObjeto,
            bairroObjeto,
            cidadeObjeto,
            ufObjeto,
            cepObjeto,
            nacionalidadeLocador,
            orgaoExpedidor,
            ufExpedicao,
            ruaLocador,
            numLocador,
            compLocador,
            bairroLocador,
            cepLocador,
            nacionalidadeLocatario,
            orgaoExpedidorLocatario,
            ufExpedicaoLocatario,
            ruaLocatario,
            numLocatario,
            compLocatario,
            bairroLocatario,
            ufLocatario,
            cepLocatario,
            cidadeLocatario,
            ufLocador,
            cidadeLocador,
            nomeCorretor,
            nacionalidadeCorretor,
            estadoCivilCorretor,
            profissaoCorretor,
            cpfCorretor,
            rgCorretor,
            orgaoExpedidorCorretor,
            ufExpedicaoCorretor,
            numCreci,
            ruaCorretor,
            numCorretor,
            cepCorretor,
            bairroCorretor,
            cidadeCorretor,
            ufCorretor,
            valorServicoCorretor,
            valorServicoEscrito,
            bancoCorretor,
            agCorretor,
            contaCorretor,
            pixCorretor,
            prazoVigencia,
            inicio,
            termino,
            valorMensal,
            vencimento,
            finalidadeLocacao,
            valorGarantiaCaucao,
            diaVencimento,
            ciaEletrica,
            bancoLocador,
            agLocador,
            contaLocador,
            titularConta,
            date,
    }: ContractDataDTO): Promise<any> {
        const templatePath = process.env.TEMPLATE_PATH;

        const data = {
            valorMensalAluguelEscrito,
            finalidade,
            locador,
            cpfLocador,
            estadoCivilLocador,
            profissaoLocador,
            rgLocador,
            locatario,
            cpfLocatario,
            estadoCivilLocatario,
            profissaoLocatario,
            rgLocatario,
            nomeConjuge,
            cpfConjuge,
            objContrato,
            endObjeto,
            numObjeto,
            bairroObjeto,
            cidadeObjeto,
            ufObjeto,
            cepObjeto,
            nacionalidadeLocador,
            orgaoExpedidor,
            ufExpedicao,
            ruaLocador,
            numLocador,
            compLocador,
            bairroLocador,
            cepLocador,
            nacionalidadeLocatario,
            orgaoExpedidorLocatario,
            ufExpedicaoLocatario,
            ruaLocatario,
            numLocatario,
            compLocatario,
            bairroLocatario,
            ufLocatario,
            cepLocatario,
            cidadeLocatario,
            ufLocador,
            cidadeLocador,
            nomeCorretor,
            nacionalidadeCorretor,
            estadoCivilCorretor,
            profissaoCorretor,
            cpfCorretor,
            rgCorretor,
            orgaoExpedidorCorretor,
            ufExpedicaoCorretor,
            numCreci,
            ruaCorretor,
            numCorretor,
            cepCorretor,
            bairroCorretor,
            cidadeCorretor,
            ufCorretor,
            valorServicoCorretor,
            valorServicoEscrito,
            bancoCorretor,
            agCorretor,
            contaCorretor,
            pixCorretor,
            prazoVigencia,
            inicio,
            termino,
            valorMensal,
            vencimento,
            finalidadeLocacao,
            valorGarantiaCaucao,
            diaVencimento,
            ciaEletrica,
            bancoLocador,
            agLocador,
            contaLocador,
            titularConta,
            date: dateProvider.date
        }

        const pdfPath = `${process.env.PDF_PATH}`;

        const options = {
            paperSize: {
                format: 'A4',
                orientation: 'portrait',
                border: '1cm'
            } 
        }

        await pdfMaker(templatePath, data, pdfPath, options);

        const fileUpload = await uploadProvider(pdfPath);

        return fileUpload;
    }
}