import { Request, Response } from 'express';
import { CreateContratoAluguelCaucaoUseCase } from './CreateContratoAluguelCaucaoUseCase';

export class CreateContratoAluguelCaucaoController {
    async handle(req: Request, res: Response): Promise<Response> {
        try {
            const {
                valorMensalAluguelEscrito,
                locador,
                cpfLocador,
                estadoCivilLocador,
                profissaoLocador,
                rgLocador,
                locatario,
                cpfLocatario,
                estadoCivilLocatario,
                profissaoLocatario,
                rgLocatario,
                nomeConjuge,
                cpfConjuge,
                finalidade,
                objContrato,
                endObjeto,
                numObjeto,
                bairroObjeto,
                cidadeObjeto,
                ufObjeto,
                cepObjeto,
                nacionalidadeLocador,
                orgaoExpedidor,
                ufExpedicao,
                ruaLocador,
                numLocador,
                compLocador,
                bairroLocador,
                cepLocador,
                nacionalidadeLocatario,
                orgaoExpedidorLocatario,
                ufExpedicaoLocatario,
                ruaLocatario,
                numLocatario,
                compLocatario,
                bairroLocatario,
                ufLocatario,
                cepLocatario,
                cidadeLocatario,
                ufLocador,
                cidadeLocador,
                nomeCorretor,
            nacionalidadeCorretor,
            estadoCivilCorretor,
            profissaoCorretor,
            cpfCorretor,
            rgCorretor,
            orgaoExpedidorCorretor,
            ufExpedicaoCorretor,
            numCreci,
            ruaCorretor,
            numCorretor,
            cepCorretor,
            bairroCorretor,
            cidadeCorretor,
            ufCorretor,
            valorServicoCorretor,
            valorServicoEscrito,
            bancoCorretor,
            agCorretor,
            contaCorretor,
            pixCorretor,
            prazoVigencia,
            inicio,
            termino,
            valorMensal,
            vencimento,
            finalidadeLocacao,
            valorGarantiaCaucao,
            diaVencimento,
            ciaEletrica,
            bancoLocador,
            agLocador,
            contaLocador,
            titularConta,
            date,
        } = req.body;

        const generatePdfUseCase = new CreateContratoAluguelCaucaoUseCase();

        const file = await generatePdfUseCase.execute({
            valorMensalAluguelEscrito,
            locador,
            cpfLocador,
            estadoCivilLocador,
            profissaoLocador,
            rgLocador,
            locatario,
            cpfLocatario,
            estadoCivilLocatario,
            profissaoLocatario,
            rgLocatario,
            nomeConjuge,
            cpfConjuge,
            finalidade,
            objContrato,
            endObjeto,
            numObjeto,
            bairroObjeto,
            cidadeObjeto,
            ufObjeto,
            cepObjeto,
            nacionalidadeLocador,
            orgaoExpedidor,
            ufExpedicao,
            ruaLocador,
            numLocador,
            compLocador,
            bairroLocador,
            cepLocador,
            nacionalidadeLocatario,
            orgaoExpedidorLocatario,
            ufExpedicaoLocatario,
            ruaLocatario,
            numLocatario,
            compLocatario,
            bairroLocatario,
            ufLocatario,
            cepLocatario,
            cidadeLocatario,
            ufLocador,
            cidadeLocador,
            nomeCorretor,
            nacionalidadeCorretor,
            estadoCivilCorretor,
            profissaoCorretor,
            cpfCorretor,
            rgCorretor,
            orgaoExpedidorCorretor,
            ufExpedicaoCorretor,
            numCreci,
            ruaCorretor,
            numCorretor,
            cepCorretor,
            bairroCorretor,
            cidadeCorretor,
            ufCorretor,
            valorServicoCorretor,
            valorServicoEscrito,
            bancoCorretor,
            agCorretor,
            contaCorretor,
            pixCorretor,
            prazoVigencia,
            inicio,
            termino,
            valorMensal,
            vencimento,
            finalidadeLocacao,
            valorGarantiaCaucao,
            diaVencimento,
            ciaEletrica,
            bancoLocador,
            agLocador,
            contaLocador,
            titularConta,
            date,
        });

        return res.json(file);
        } catch (error) {
            console.error('Erro no controller de caução:', error);
            return res.status(500).json({ 
                error: 'Erro interno do servidor ao gerar PDF',
                message: error instanceof Error ? error.message : 'Erro desconhecido'
            });
        }
    }
}
